# Generated by Django 6.0.6 on 2026-07-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='long_description',
            field=models.TextField(blank=True, help_text='Used for Overview & Description details'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='short_description',
            field=models.TextField(blank=True, help_text='Used for Usage & Storage advice'),
        ),
    ]
