# Generated by Django 6.0.6 on 2026-07-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='long_description',
            field=models.JSONField(blank=True, default=dict, help_text='JSON for Overview, About, Highlights & Detailed Specs'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='JSON for promotional flags (is_hot_deal, is_best_selling, is_top_rated, is_featured) and pack meta'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='short_description',
            field=models.JSONField(blank=True, default=dict, help_text='JSON for Usage, Dosage, Storage & Safety Advice'),
        ),
    ]
