# Generated by Django 6.0.6 on 2026-08-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productvariant_long_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsAnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='⚡ Free Home Delivery on orders over ৳1,000!', max_length=255)),
                ('bg_theme', models.CharField(default='Midnight', max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CmsHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('badge', models.CharField(blank=True, default='', max_length=100)),
                ('cta_text', models.CharField(default='Shop Now', max_length=100)),
                ('cta_link', models.CharField(default='/products', max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
