# Generated by Django 6.0.6 on 2026-08-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cmsannouncementbar_cmsheroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsheroslide',
            name='slide_type',
            field=models.CharField(choices=[('main_hero', 'Main Hero Banner (Large Left)'), ('side_top', 'Side Stack Banner (Top Right)'), ('side_bottom_left', 'Side Stack (Bottom Left)'), ('side_bottom_right', 'Side Stack (Bottom Right)')], default='main_hero', max_length=50),
        ),
        migrations.AlterField(
            model_name='cmsheroslide',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
