# Generated by Django 6.0.6 on 2026-08-16 04:40

# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cmsheroslide_slide_type_alter_cmsheroslide_image_url'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'approval_status', 'deleted_at'], name='ph_products_status_659e35_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status', 'deleted_at'], name='ph_products_categor_bbe51e_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['status', 'price'], name='ph_product__status_6d9f13_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'status'], name='ph_product__product_461831_idx'),
        ),
    ]
