# Generated by Django 6.0.6 on 2026-07-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_order_n_1336be_idx',
            old_name='order_order_n_06f120_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_custome_6c3a7f_idx',
            old_name='order_custome_7c3d15_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_order_s_0d3802_idx',
            old_name='order_order_s_15dbf1_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_payment_050188_idx',
            old_name='order_payment_57a3c1_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_created_77e2b9_idx',
            old_name='order_created_6dbd10_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='profiles.riderprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumer_order', to='profiles.consumerprofile'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='profiles.vendorprofile'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
