# Generated by Django 6.0.6 on 2026-07-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_order_n_06f120_idx_orders_order_n_1336be_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderstatushistory',
            new_name='order_statu_order_i_8ab903_idx',
            old_name='orders_orde_order_i_f43086_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstatushistory',
            new_name='order_statu_status_9fc6d2_idx',
            old_name='orders_orde_status_3c2037_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstatushistory',
            new_name='order_statu_created_0970b5_idx',
            old_name='orders_orde_created_5bf538_idx',
        ),
        migrations.AlterModelTable(
            name='orderstatushistory',
            table='order_status_history',
        ),
    ]
