# Generated by Django 6.0.6 on 2026-08-02 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_orders_orde_order_i_f43086_idx_order_statu_order_i_8ab903_idx_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount_bdt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=100)),
                ('account_details', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('transaction_trx_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='profiles.vendorprofile')),
            ],
            options={
                'db_table': 'vendor_payout_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
