# Generated by Django 6.0.6 on 2026-07-05 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together_alter_cartitem_id_and_more'),
        ('products', '0002_alter_inventory_vendor_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_variant'), name='unique_cart_product_variant'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='ph_cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='ph_cart_items',
        ),
    ]
