# Generated by Django 6.0.6 on 2026-07-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_id_alter_cartitem_product_variant_and_more'),
        ('products', '0002_alter_inventory_vendor_alter_product_brand_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product_variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='profiles.vendorprofile'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_variant', 'vendor'), name='unique_cart_product_variant_vendor'),
        ),
    ]
