# Generated by Django 6.0.6 on 2026-07-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_unique_cart_product_variant_and_more'),
        ('products', '0002_alter_inventory_vendor_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product_variant_vendor',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_variant'), name='unique_cart_product_variant'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='vendor',
        ),
    ]
