# Generated by Django 6.0.6 on 2026-07-12 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_unique_cart_product_variant_vendor_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='consumer_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='profiles.consumerprofile'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
    ]
