# Generated by Django 6.0.6 on 2026-07-12 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0002_rename_order_order_n_06f120_idx_orders_order_n_1336be_idx_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='profiles.consumerprofile')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='orders.order')),
            ],
            options={
                'db_table': 'coupon_usages',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['coupon'], name='coupon_usag_coupon__f4b516_idx'), models.Index(fields=['consumer'], name='coupon_usag_consume_508da1_idx'), models.Index(fields=['order'], name='coupon_usag_order_i_7b9192_idx'), models.Index(fields=['used_at'], name='coupon_usag_used_at_252e58_idx')],
            },
        ),
    ]
