# Generated by Django 6.0.6 on 2026-08-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_securityauditlog_staffrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='authentication.staffrole'),
        ),
    ]
